clear;
clc;
% close all;

n_method=9;
font_size=12;

addpath('results\');
load results_cod-rna_min_max_scaling_large_aaai23.mat

results_size=results(:,1);

method_name=["SeDuMi (8)" ...
    'MOSEK (8)' ...
    'CDCS (8)' ...
    'BCR' ...
    'SDcut' ...
    'CDCS (20)' ...
    '\color{black}\bfGDPA' ...
    'GLR-box' ...
    'SNS'];

ncolors = distinguishable_colors(n_method);
method_ii=[1 2 3 6 4 5 8 9 7];
figure();hold on;
for i=1:n_method % number of methods
    if i<=4
        plot(results(1:6,1),results(1:6,method_ii(i)+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','+',...
            'color',ncolors(method_ii(i),:),'DisplayName',num2str(method_name(method_ii(i))));
    elseif i>4 && i<=5 
        plot(results(1:6,1),results(1:6,method_ii(i)+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','s','color',ncolors(method_ii(i),:),'DisplayName',num2str(method_name(method_ii(i))));
    elseif i==6
        plot(results(1:6,1),results(1:6,method_ii(i)+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','p','color',ncolors(method_ii(i),:),'DisplayName',num2str(method_name(method_ii(i)))); 
    elseif i==9
        plot(results(1:6,1),results(1:6,method_ii(i)+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','x',...
            'color',ncolors(method_ii(i),:),'DisplayName',num2str(method_name(method_ii(i))));        
    else
        plot(results(:,1),results(:,method_ii(i)+1),...
            'LineStyle','none',...
            'LineWidth',1,...
            'Marker','o','color',ncolors(method_ii(i),:),'DisplayName',num2str(method_name(method_ii(i))));
    end
end

xlabel('problem size', 'FontSize', font_size);
ylabel('runtime (ms)', 'FontSize', font_size);
set(gca,'fontname','times', 'FontSize', font_size)  % Set it to times
xlim([min(results(:,1)) max(results(:,1))]);
results(:,1)=[];
results(results==0)=[];
ylim([min(vec(results)) max(vec(results))]);
grid on;
set(gca, 'xScale', 'log')
set(gca, 'YScale', 'log')
legend;